import { CalendarDays, CloudDrizzle, CloudRain, CloudSun, Cloudy, Command, CommandIcon, Droplets, Eye, Gauge, Navigation, Search, Snowflake, SunDim, SunIcon, Sunset, Thermometer, ThermometerSun, UserRound, Wind } from "lucide-react";

export const sun = <SunIcon size={25}/>;
export const Sun = <SunDim size={25}/>;
export const calender = <CalendarDays size={25}/>;
export const people = <UserRound size={25}/>;
export const thermometer = <Thermometer size={30}/>;
export const droplets = <Droplets size={25}/>;
export const eye = <Eye size={25}/>;
export const gauge = <Gauge size={25}/>;
export const wind = <Wind size={25}/>;
export const sunset = <Sunset size={25}/>;
export const thermo = <ThermometerSun size={25}/>;
export const navigation = <Navigation size={15}/>;
export const cloudy = <Cloudy size={25}/>;
export const snow = <Snowflake size={30}/>;
export const drizzleIcon = <CloudDrizzle size={25}/>;
export const searchIcon = <Search />;
export const commandIcon = <Command size={14}/>;
export const clearSky = <CloudSun size={30}/>;
export const rain = <CloudRain size={30} />;