// "use client";
// import React from 'react';

// const AIContent = () => {
//   // Hardcoded data simulating an AI-generated response about weather for one city
//   const aiWeatherData = {
//     id: 1,
//     location: "New York, NY",
//     prompt: "Current weather and forecast for New York, NY",
//     response: "The current weather in New York, NY is sunny with a temperature of 75°F (24°C). There is a light breeze from the northwest. The forecast for the next few days includes clear skies with temperatures ranging from 70°F to 80°F. It's a great time to enjoy outdoor activities.",
//     model: "WeatherGPT",
//     generatedAt: new Date().toISOString(),
//   };

//   // Defining a constant for the title
//   const title = "AI Weather Insight for New York, NY";

//   return (
//     <div className="ai-content pt-6 px-4 border rounded-lg flex flex-col gap-4 drop-shadow-2xl dark:bg-black/50 dark:backdrop-blur-sm shadow-sm bg-slate-100 backdrop-blur-sm h-[500px] w-[300px]">
//       <h2 className="text-xl font-bold mb-2">{title}</h2>
//       <div className="overflow-y-auto flex-grow">
//         <div key={aiWeatherData.id} className="ai-article mb-4 pb-2 border-b last:border-b-0">
//           <h3 className="text-lg font-semibold mb-1">{aiWeatherData.prompt}</h3>
//           <p className="text-sm dark:text-white 0 mb-1">{aiWeatherData.response}</p>
//           <p className="text-xs text-gray-500 dark:text-gray-400">{`Generated by ${aiWeatherData.model} on ${new Date(aiWeatherData.generatedAt).toLocaleDateString()}`}</p>
//         </div>
//       </div>
//     </div>
//   );
// };

// export default AIContent;
"use client";
import React from 'react';
import { useGlobalContext } from "@/app/Context/globalContext";
import { Skeleton } from "@/components/ui/skeleton";

function AIContent() {
  const { aiWeatherData } = useGlobalContext();

  if (!aiWeatherData) {
    return (
      <div className="pt-6 px-4 border rounded-lg flex flex-col justify-between drop-shadow-2xl dark:bg-dark-grey shadow-sm h-full dark:shadow-none gap-2 backdrop-blur-sm">
        <Skeleton className="w-full h-[20px] rounded-full bg-slate-100 backdrop-blur-sm" />
        <Skeleton className="w-full h-[20px] rounded-full" />
      </div>
    );
  }

  const { location, prompt, information, model, generatedAt } = aiWeatherData;

  return (
    <div className="ai-content pt-6 px-4 border rounded-lg flex flex-col gap-4 drop-shadow-2xl dark:bg-black/50 dark:backdrop-blur-sm shadow-sm bg-slate-100 backdrop-blur-sm h-[500px] w-[300px]">
      <h2 className="text-xl font-bold mb-2">{`AI Weather Insight for ${location}`}</h2>
      <div className="overflow-y-auto flex-grow">
        <div className="ai-article mb-4 pb-2 border-b last:border-b-0">
          <h3 className="text-lg font-semibold mb-1">{prompt}</h3>
          <p className="text-sm dark:text-white text-gray-600 mb-1">{information}</p>
          <p className="text-xs text-gray-500 dark:text-gray-400">{`Generated by ${model} on ${new Date(generatedAt).toLocaleDateString()}`}</p>
        </div>
      </div>
    </div>
  );
}

export default AIContent;
