
"use client";
import React from 'react';
import { useGlobalContext } from "@/app/Context/globalContext";
import { Skeleton } from "@/components/ui/skeleton";

function AIContent() {
  const { aiWeatherData } = useGlobalContext();

  if (!aiWeatherData) {
    return (
      <div className="pt-6 px-4 border rounded-lg flex flex-col justify-between drop-shadow-2xl dark:bg-dark-grey shadow-sm h-full dark:shadow-none gap-2 backdrop-blur-sm">
        <Skeleton className="w-full h-[20px] rounded-full bg-slate-100 backdrop-blur-sm" />
        <Skeleton className="w-full h-[20px] rounded-full" />
      </div>
    );
  }

  const { location, prompt, information, model, generatedAt } = aiWeatherData;

  return (
    <div className="ai-content pt-6 px-4 border rounded-lg flex flex-col gap-4 drop-shadow-2xl dark:bg-black/50 dark:backdrop-blur-sm shadow-sm bg-slate-100 backdrop-blur-sm h-[500px] w-[300px]">
      <h2 className="text-xl font-bold mb-2">{`AI Weather Insight for ${location}`}</h2>
      <div className="overflow-y-auto flex-grow">
        <div className="ai-article mb-4 pb-2 border-b last:border-b-0">
          <h3 className="text-lg font-semibold mb-1">{prompt}</h3>
          <p className="text-sm dark:text-white text-gray-600 mb-1">{information}</p>
          <p className="text-xs text-gray-500 dark:text-gray-400">{`Generated by ${model} on ${new Date(generatedAt).toLocaleDateString()}`}</p>
        </div>
      </div>
    </div>
  );
}

export default AIContent;
